version: '3'

services:
  postgresdb:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # uncomment if you need to connect to db outside of docker, eg: pgadmin
    # ports:
    #   - "127.0.0.1:${DB_PROXY_PORT}:5432"
    # uncomment to persist db data between downs
    # volumes:
    #  - ./db-data/:/var/lib/postgresql/data
    # uncomment for query logging
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  appserver:
    container_name: ${COMPOSE_PROJECT_NAME}_server
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - ../../.env
    ports:
      - "127.0.0.1:${LISTEN_PORT}:8000"
    depends_on:
      - postgresdb
    volumes:
      - ../../:/app
      - ../../media/:/appdata/media
