#!/usr/bin/env bash

until pg_isready -h postgresdb -p 5432 -U "${DB_USER}" 2>/dev/null; do
    echo "waiting for postgres"
    sleep 1
done

# python manage.py collectstatic --no-input
# python manage.py migrate

[ -z ${ADMIN_EMAIL+x} ] | [ -z ${ADMIN_PASSWORD+x} ] || python manage.py admin_user --email $ADMIN_EMAIL --password $ADMIN_PASSWORD

exec python manage.py runserver "0.0.0.0:8000"
