version: '3'

services:
  postgresdb:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PROXY_PORT}:5432"
    restart: unless-stopped
    volumes:
      - ./db-data/:/var/lib/postgresql/data

  appserver:
    container_name: ${COMPOSE_PROJECT_NAME}_server
    image: ${DOCKER_IMAGE_URL}
    env_file:
      - .env
    ports:
      - "127.0.0.1:${LISTEN_PORT}:3030"
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media
    logging:
      driver: syslog
      options:
        syslog-address: "udp://localhost:514"
        tag: "${COMPOSE_PROJECT_NAME}_server|{{.ContainerName}}|{{.FullID}}"

  relay-coston:
    container_name: ${COMPOSE_PROJECT_NAME}_relay-coston
    image: ${DOCKER_IMAGE_URL}
    command: start-relay coston
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media

  relay-sepolia:
    container_name: ${COMPOSE_PROJECT_NAME}_relay-sepolia
    image: ${DOCKER_IMAGE_URL}
    command: start-relay sepolia
    env_file:
      - .env
    depends_on:
      - postgresdb
    restart: unless-stopped
    volumes:
      - ./static/:/appdata/static
      - ./media/:/appdata/media
