# Generated by Django 5.0.1 on 2024-03-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chain",
                    models.CharField(choices=[("coston", "Coston"), ("sepolia", "Sepolia")], max_length=7, unique=True),
                ),
                ("number", models.PositiveIntegerField()),
                ("timestamp", models.PositiveIntegerField()),
            ],
        ),
    ]
