# Generated by Django 5.0.1 on 2024-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chain",
                    models.CharField(choices=[("coston", "Coston"), ("sepolia", "Sepolia")], max_length=7, unique=True),
                ),
                ("timestamp", models.PositiveIntegerField()),
                ("blockNumber", models.PositiveIntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
                ("uid", models.PositiveIntegerField()),
                ("relayInitiator", models.CharField(max_length=42)),
                ("relayTarget", models.CharField(max_length=42)),
                ("additionalCalldata", models.BinaryField()),
                ("sourceToken", models.CharField(max_length=42)),
                ("targetToken", models.CharField(max_length=42)),
                ("amount", models.PositiveIntegerField()),
            ],
        ),
    ]
