# Generated by Django 5.0.1 on 2024-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay", "0002_relaycall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relaycall",
            name="chain",
            field=models.CharField(choices=[("coston", "Coston"), ("sepolia", "Sepolia")], max_length=7),
        ),
    ]
